title = 'Mistletoe'
baseURL = 'https://mistletoe.dev/'
languageCode = 'en-us'

theme = 'PaperMod'

[params]
disableThemeToggle = true
defaultTheme = 'light'

[params.label]
text = 'Mistletoe Package Manager'
icon = '/logo.png'
iconHeight = 80

[params.homeInfoParams]
Content = """
[![GitHub](https://img.shields.io/badge/GitHub-mistletoe-green)](https://github.com/gsfraley/mistletoe)

# --------------
# Overview

**Mistletoe** is a Kubernetes package manager that goes about things in a different way than the rest of the
ecosystem. It's built around a runtime where the packages are **WebAssembly** modules:

```rust
misthusk_headers! {"
  name: example-namespace
  labels:
    mistletoe.dev/group: mistletoe-examples
"}

#[derive(Deserialize)]
struct InputConfig {
    name: String,
}

pub fn generate(input_config: InputConfig) -> MistHuskResult {
    let output = MistHuskOutput::new()
        .with_file("namespace.yaml".to_string(), formatdoc!{"
            apiVersion: apps/v1
            kind: Namespace
            metadata:
              name: {0}
        ", input_config.name});

    Ok(output)
}
```

If you take the above package and run it with:

```sh
mistctl generate my-namespace -p ./my-package.wasm
```

You get the following YAML back:

```yaml
apiVersion: apps/v1
kind: Namespace
metadata:
  name: my-namespace
```

This is one of a nearly-unlimited number of ways to write a package.  ***All you need is a language with a
YAML parser that can compile to WebAssembly.***

# --------------
# Roadmap

**Mistletoe** is still early on in the development lifecycle.  The above example works without issue, but
there are a handful of things that need to be addressed before it could reasonably be opened up for use:

1. The `mistctl` utility currently only supports YAML generation -- it should be expanded to support
installation to clusters.  This also implies all the usual goodies around lifecycle management, notably
upgrades and uninstallation.
2. The package manager is currently confined to packages that exist on the local filesystem.  We'll need to
attach a registry system for users to pull and run packages by ref, not to mention some starting packages
to demonstrate practical development and use.
3. Need documentation, documentation, and more documentation.  The only way to guarantee adoption is to
provide best-in-class documentation covering everything from general usage, to package development in
multiple languages, to the nitty-gritty advanced information about the runtime for eager hackers.

There's all that, as well as a number of less-important, but also-desired efforts worth evaluating:

1. Dependencies!  We can get a lot more value by adding a way for packages to declare and call dependency
packages for easier composition of systems.
2. Since the runtime is pretty open, we could theoretically package other package managers.  This means we
could provide a system to install Helm packages as if they were any other Mistletoe package.
"""
